### ISSUE TITLE
命令行执行报错..

### ISSUE THREAD

**Issue by reb00t2018** [feiyu563/nbping#1]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x10f00ea]

goroutine 19 [running]:
main.(*ping).Close(0xc0000c2000, 0x1217e20, 0x20)
	/Users/xxxx/nbping/nbping.go:176 +0x2a
main.IPpingStart(0xc000090240, 0xe, 0xc0000740c0, 0xc00006e200)
	/Users/xxxx/nbping/nbping.go:65 +0x1eb
created by main.main
	/Users/xxxt/nbping/nbping.go:111 +0x760
exit status 2

	for _, ip := range ips {
		status <- 1
		go IPpingStart(ip, req, status)     // 此行报错
		//IPpingStart(ip, req, status)
	}

**Comment by reb00t2018** [comment]
IPpingStart 函数里面
defer ping.Close()  这行的问题，有时候执行脚本报错，有时候不报错。这行注释掉完全不报错了.
